module.exports = [
    { group: 'Layout', name: 'u-linear-layout', alias: '线性布局' },
    { group: 'Layout', name: 'u-grid-layout', alias: '栅格布局' },
    { group: 'Layout', name: 'u-multi-layout', alias: '分栏布局' },

    { group: 'Navigation', name: 'u-crumb', alias: '面包屑' },
    { group: 'Navigation', name: 'u-sidebar', alias: '侧边栏' },
    { group: 'Navigation', name: 'u-navbar-multi', alias: '导航栏' },
    { group: 'Navigation', name: 'u-dropdown', alias: '下拉菜单' },
    { group: 'Navigation', name: 'u-toc', alias: '目录' },
    { group: 'Navigation', name: 'u-anchor', alias: '锚点' },

    { group: 'Container', name: 'u-router-view', alias: '子页面容器' },
    { group: 'Container', name: 'u-iframe', alias: 'Iframe' },
    { group: 'Container', name: 'u-panel', alias: '面板' },
    { group: 'Container', name: 'u-collapse', alias: '折叠面板' },
    { group: 'Container', name: 'u-card', alias: '卡片' },

    { group: 'Display', name: 'u-text', alias: '文本' },
    { group: 'Display', name: 'u-link', alias: '链接' },
    { group: 'Display', name: 'u-button', alias: '按钮' },
    // { group: 'Display', name: 'i-icon', alias: '图标' },
    { group: 'Display', name: 'i-ico', alias: '图标' },
    { group: 'Display', name: 'u-gallery', alias: '画廊' },
    { group: 'Display', name: 'u-label', alias: '标签' },
    { group: 'Display', name: 'u-badge', alias: '徽章' },
    { group: 'Display', name: 'u-carousel', alias: '幻灯片' },
    { group: 'Display', name: 'u-info-list', alias: '详情列表' },
    { group: 'Display', name: 'u-image', alias: '图片展示' },
    { group: 'Display', name: 'u-alert', alias: '公告' },
    { group: 'Display', name: 'u-count-down', alias: '计时器' },
    { group: 'Display', name: 'u-divider', alias: '分割线' },
    { group: 'Display', name: 'u-timeline', alias: '时间线' },

    { group: 'Table', name: 'u-table-view', alias: '数据表格' },
    { group: 'Table', name: 'u-list-view', alias: '数据列表' },
    { group: 'Table', name: 'u-grid-view', alias: '数据网格' },
    { group: 'Table', name: 'u-calendar-view', alias: '日历' },
    { group: 'Table', name: 'u-list-components', alias: '组件列表' },

    { group: 'Form', name: 'u-form', alias: '表单' },
    { group: 'Form', name: 'u-input', alias: '单行输入' },
    { group: 'Form', name: 'u-number-input', alias: '数字输入' },
    { group: 'Form', name: 'u-textarea', alias: '多行输入' },
    { group: 'Form', name: 'u-radios', alias: '单选组' },
    { group: 'Form', name: 'u-switch', alias: '开关' },
    { group: 'Form', name: 'u-checkboxes', alias: '多选组' },
    { group: 'Form', name: 'u-capsules', alias: '胶囊' },
    { group: 'Form', name: 'u-select', alias: '选择框' },
    { group: 'Form', name: 'u-tree-select-new', alias: '树选择器' },
    { group: 'Form', name: 'u-rate', alias: '评分' },
    { group: 'Form', name: 'u-combo-slider', alias: '滑块' },
    { group: 'Form', name: 'u-uploader', alias: '文件上传' },
    { group: 'Form', name: 'u-validator', alias: '验证器' },

    { group: 'Selector', name: 'u-tabs', alias: '选项卡' },
    { group: 'Selector', name: 'u-selectable-steps', alias: '步骤条' },
    { group: 'Selector', name: 'u-pagination', alias: '翻页器' },
    { group: 'Selector', name: 'u-cascader', alias: '级联选择' },
    { group: 'Selector', name: 'u-region-select', alias: '地区选择' },
    { group: 'Selector', name: 'u-tree-view-new', alias: '树形视图' },
    { group: 'Selector', name: 'u-transfer', alias: '穿梭框' },
    { group: 'Selector', name: 'u-date-picker', alias: '日期选择' },
    { group: 'Selector', name: 'u-time-picker', alias: '时间选择' },
    { group: 'Selector', name: 'u-date-time-picker', alias: '日期时间选择' },

    { group: 'Chart', name: 'u-linear-progress', alias: '线形进度条' },
    { group: 'Chart', name: 'u-circular-progress', alias: '圆型进度条' },

    // { group: 'Feedback', name: 'u-popup', alias: '弹出框' },
    { group: 'Feedback', name: 'u-popup-combination', alias: '弹出框' },
    { group: 'Feedback', name: 'u-modal', alias: '弹窗' },
    { group: 'Feedback', name: 'u-drawer', alias: '抽屉' },

    { group: 'Effects', name: 'e-watermark', alias: '水印' },
    { group: 'Effects', name: 'u-copy', alias: '复制' },

    { group: 'Process', name: 'u-taskbox', alias: '任务箱' },
];
