module.exports = [
    { group: 'Layout', name: 'u-linear-layout', alias: '线性布局', show: true },
    { group: 'Layout', name: 'u-absolute-layout', alias: '自由布局', show: true },
    { group: 'Layout', name: 'u-grid-layout', alias: '栅格布局', show: true },
    { group: 'Layout', name: 'u-multi-layout', alias: '分栏布局', show: true },

    { group: 'Navigation', name: 'u-crumb', alias: '面包屑', show: true },
    { group: 'Navigation', name: 'u-sidebar', alias: '侧边栏', show: true },
    { group: 'Navigation', name: 'u-navbar-multi', alias: '导航栏', show: true },
    { group: 'Navigation', name: 'u-dropdown', alias: '下拉菜单', show: true },
    { group: 'Navigation', name: 'u-toc', alias: '目录', show: true },
    { group: 'Navigation', name: 'u-anchor', alias: '锚点', show: true },

    { group: 'Container', name: 'u-router-view', alias: '子页面容器', show: true },
    { group: 'Container', name: 'u-iframe', alias: 'Iframe', show: true },
    { group: 'Container', name: 'u-panel', alias: '面板', show: true },
    { group: 'Container', name: 'u-collapse', alias: '折叠面板', show: true },
    { group: 'Container', name: 'u-card', alias: '卡片', show: true },

    { group: 'Display', name: 'u-text', alias: '文本', show: true },
    { group: 'Display', name: 'u-link', alias: '链接', show: true },
    { group: 'Display', name: 'u-button', alias: '按钮', show: true },
    // { group: 'Display', name: 'i-icon', alias: '图标', show: true },
    { group: 'Display', name: 'i-ico', alias: '图标', show: true },
    { group: 'Display', name: 'u-gallery', alias: '画廊', show: true },
    { group: 'Display', name: 'u-label', alias: '标签', show: true },
    { group: 'Display', name: 'u-badge', alias: '徽章', show: true },
    { group: 'Display', name: 'u-carousel', alias: '幻灯片', show: true },
    { group: 'Display', name: 'u-info-list', alias: '详情列表', show: true },
    { group: 'Display', name: 'u-image', alias: '图片展示', show: true },
    { group: 'Display', name: 'u-alert', alias: '公告', show: true },
    { group: 'Display', name: 'u-count-down', alias: '计时器', show: true },
    { group: 'Display', name: 'u-divider', alias: '分割线', show: true },
    { group: 'Display', name: 'u-timeline', alias: '时间线', show: true },

    { group: 'Table', name: 'u-table-view', alias: '数据表格', show: true },
    { group: 'Table', name: 'u-list-view', alias: '数据列表', show: true },
    { group: 'Table', name: 'u-grid-view', alias: '数据网格', show: true },
    { group: 'Table', name: 'u-calendar-view', alias: '日历', show: true },
    { group: 'Table', name: 'u-list-components', alias: '组件列表', show: true },

    { group: 'Form', name: 'u-form', alias: '表单', show: true },
    { group: 'Form', name: 'u-input', alias: '单行输入', show: true },
    { group: 'Form', name: 'u-number-input', alias: '数字输入', show: true },
    { group: 'Form', name: 'u-textarea', alias: '多行输入', show: true },
    { group: 'Form', name: 'u-radios', alias: '单选组', show: true },
    { group: 'Form', name: 'u-switch', alias: '开关', show: true },
    { group: 'Form', name: 'u-checkboxes', alias: '多选组', show: true },
    { group: 'Form', name: 'u-capsules', alias: '胶囊', show: true },
    { group: 'Form', name: 'u-select', alias: '选择框', show: true },
    { group: 'Form', name: 'u-tree-select-new', alias: '树选择器', show: true },
    { group: 'Form', name: 'u-rate', alias: '评分', show: true },
    { group: 'Form', name: 'u-combo-slider', alias: '滑块', show: true },
    { group: 'Form', name: 'u-uploader', alias: '文件上传', show: true },
    { group: 'Form', name: 'u-validator', alias: '验证器', show: true },

    { group: 'Selector', name: 'u-tabs', alias: '选项卡', show: true },
    { group: 'Selector', name: 'u-selectable-steps', alias: '步骤条', show: true },
    { group: 'Selector', name: 'u-pagination', alias: '翻页器', show: true },
    { group: 'Selector', name: 'u-cascader', alias: '级联选择', show: true },
    { group: 'Selector', name: 'u-region-select', alias: '地区选择', show: true },
    { group: 'Selector', name: 'u-tree-view-new', alias: '树形视图', show: true },
    { group: 'Selector', name: 'u-transfer', alias: '穿梭框', show: true },
    { group: 'Selector', name: 'u-date-picker', alias: '日期选择', show: true },
    { group: 'Selector', name: 'u-time-picker', alias: '时间选择', show: true },
    { group: 'Selector', name: 'u-date-time-picker', alias: '日期时间选择', show: true },

    { group: 'Chart', name: 'u-linear-progress', alias: '线形进度条', show: true },
    { group: 'Chart', name: 'u-circular-progress', alias: '圆型进度条', show: true },

    // { group: 'Feedback', name: 'u-popup', alias: '弹出框', show: true },
    { group: 'Feedback', name: 'u-popup-combination', alias: '弹出框', show: true },
    { group: 'Feedback', name: 'u-modal', alias: '弹窗', show: true },
    { group: 'Feedback', name: 'u-drawer', alias: '抽屉', show: true },

    { group: 'Effects', name: 'e-watermark', alias: '水印', show: true },
    { group: 'Effects', name: 'u-copy', alias: '复制', show: true },

    { group: 'Process', name: 'u-taskbox', alias: '任务箱', show: true },
];
