#!/usr/bin/env node

const path = require('path');
const shell = require('shelljs');

const configPath = path.resolve(__dirname, 'vusion.config.js');
shell.cd(path.resolve(__dirname, '../src'));
shell.exec(`vusion build -c "${configPath}"`);
// shell.cd(path.resolve(__dirname, '../src'));
// shell.exec(`vusion build -c "${configPath}"`);
// shell.cd(path.resolve(__dirname, '../src'));
// shell.exec(`vusion build -c "${configPath}"`);
