#!/usr/bin/env node

const path = require('path');
const shell = require('shelljs');

const program = require('commander');
program
    .option('-t, --theme <theme>', 'Theme')
    .parse(process.argv);

let theme;
if (program.theme === 'src')
    theme = 'default';
else
    theme = program.theme;

const outputPath = path.resolve(__dirname, '../cloud-ui');
shell.rm('-rf', outputPath);
shell.cp('-r', path.resolve(__dirname, 'static'), outputPath);

const configPath = path.resolve(__dirname, 'vusion.config.js');

if (theme)
    shell.exec(`npx vusion build -c "${configPath}" -t ${theme}`);
else {
    shell.exec(`npx vusion build -c "${configPath}" -t default`);
    shell.exec(`npx vusion build -c "${configPath}" -t dark`);
    shell.exec(`npx vusion build -c "${configPath}" -t seagreen`);
    shell.exec(`npx vusion build -c "${configPath}" -t cobalt`);
}
