#!/usr/bin/env node

const path = require('path');
const shell = require('shelljs');

const program = require('commander');
program
    .option('-t, --theme <theme>', 'Theme')
    .parse(process.argv);

let theme;
if (!program.theme || program.theme === 'src')
    theme = 'default';
else
    theme = program.theme;

const outputPath = path.resolve(__dirname, '../cloud-ui');
shell.rm('-rf', outputPath);
shell.cp('-r', path.resolve(__dirname, 'static'), outputPath);

const configPath = path.resolve(__dirname, 'vusion.config.js');
const cmd = `npx vusion dev -p 9002 -c "${configPath}" -t ${theme}`;
console.info(cmd);
shell.exec(cmd);
