#!/usr/bin/env node

const path = require('path');
const shell = require('shelljs');

const theme = process.argv[process.argv.length - 1] || './src';

const outputPath = path.resolve(__dirname, '../cloud-ui');
shell.rm('-rf', outputPath);
shell.cp('-r', path.resolve(__dirname, 'static'), outputPath);

const themePath = path.resolve(process.cwd(), theme);
if (!shell.test('-d', themePath))
    throw new Error(`Cannot find "${themePath}"!`);
console.info('cd', themePath);
shell.cd(themePath);

const configPath = path.resolve(__dirname, 'vusion.config.js');
const cmd = `vusion dev -p 9002 -c "${configPath}"`;
console.info(cmd);
shell.exec(cmd);
