name: Build and Upload

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current branch name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Get version from branch name
        run: echo "VERSION=$(echo ${{ env.BRANCH_NAME }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build:theme

      # 创建一个临时目录
      - name: Create temp dir
        run: mkdir temp && cp -r ./dist-theme ./temp/dist-theme && cp -r ./src ./temp/src

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: 'cloud-ui.vusion@${{ env.VERSION$"v" }}'
          path: temp
